/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

// jsonb columns are written as pre-serialized JSON strings (never raw JS arrays, which pg would send as SQL arrays).
export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: Generated<string>;
  id: Generated<string>;
  kind: string;
  name: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Allocations {
  amount: Numeric;
  amount_in_target_currency: Numeric | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: string;
  from_document_id: string;
  fx_rate_id: string | null;
  id: Generated<string>;
  order_id: string | null;
  target_currency: string | null;
  to_document_id: string | null;
  weight_kg: Numeric | null;
}

export interface AuditLog {
  action: string;
  after: Json | null;
  at: Generated<Timestamp>;
  before: Json | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  entity: string;
  entity_id: string | null;
  id: Generated<string>;
  reason: string | null;
  user_id: string | null;
}

export interface BotLog {
  chat_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  detail: string | null;
  id: Generated<string>;
  kind: string;
}

export interface BundleLines {
  bars: number | null;
  bundle_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  filler_mm: Numeric | null;
  id: Generated<string>;
  length_m: Numeric | null;
  order_line_id: string | null;
  product_id: string;
  sort: Generated<number>;
  weight_kg: Numeric | null;
}

export interface Bundles {
  code: string;
  code_is_temp: Generated<boolean>;
  color: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision: string | null;
  decision_note: string | null;
  defect: string | null;
  draft: Generated<boolean>;
  factory_party_id: string | null;
  form: Generated<string>;
  id: Generated<string>;
  location_id: string;
  measured_filler_mm: Numeric | null;
  measured_length_m: Numeric | null;
  note: string | null;
  origin_bundle_ids: Generated<string[]>;
  packaging_kg: Numeric | null;
  production_run_id: string | null;
  qc_note: string | null;
  raw_weight_kg: Numeric | null;
  reported_at: Generated<Timestamp>;
  reserved_order_line_id: string | null;
  source: Generated<string>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  warnings: Generated<Json>;
  weight_kg: Numeric;
}

export interface CoatingRunItems {
  bars_returned: number | null;
  bundle_id: string;
  coated_kg: Numeric | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  gain_needs_review: Generated<boolean>;
  id: Generated<string>;
  note: string | null;
  qc: string | null;
  raw_kg: Numeric;
  returned_at: Timestamp | null;
  run_id: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface CoatingRuns {
  basis_reason: string | null;
  closed_at: Timestamp | null;
  closed_by: string | null;
  color_code: string | null;
  contract_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  due_at: Timestamp | null;
  fee_document_id: string | null;
  id: Generated<string>;
  includes_material: boolean | null;
  input_basis: Generated<string>;
  input_basis_kg: Numeric | null;
  material_lot_id: string | null;
  material_units: Numeric | null;
  note: string | null;
  number: string;
  party_id: string;
  rate_currency: Generated<string>;
  rate_per_kg: Numeric | null;
  sent_at: Generated<Timestamp>;
  service: string;
  status: Generated<string>;
  transfer_id: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Contracts {
  allowed_loss_percent: Numeric | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: Generated<string>;
  fixed_fee: Numeric | null;
  freight_payer: string | null;
  id: Generated<string>;
  includes_material: boolean | null;
  note: string | null;
  party_id: string;
  rate_per_kg: Numeric | null;
  rework_payer: string | null;
  scrap_credit_rate: Numeric | null;
  scrap_owner: string | null;
  service: string;
  updated_at: Generated<Timestamp>;
  valid_from: Timestamp;
  valid_to: Timestamp | null;
  version: Generated<number>;
  weight_basis: string | null;
}

export interface CorrectionRequests {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  entity: string;
  entity_id: string;
  id: Generated<string>;
  reason: string;
  resolution: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Counters {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  kind: string;
  last_value: number;
  year: number;
}

export interface DailyReports {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  date: Timestamp;
  generated_at: Generated<Timestamp>;
  id: Generated<string>;
  sent_to_telegram_at: Timestamp | null;
  snapshot: Json;
}

export interface DieEvents {
  at: Generated<Timestamp>;
  bundle_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  detail: string | null;
  die_id: string;
  id: Generated<string>;
  kind: string;
  measured_filler_mm: Numeric | null;
  production_run_id: string | null;
}

export interface DieOrders {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: Generated<string>;
  customer_party_id: string | null;
  die_id: string | null;
  due_date: Timestamp | null;
  id: Generated<string>;
  maker_cost: Numeric | null;
  maker_party_id: string | null;
  note: string | null;
  number: string;
  order_line_id: string | null;
  purchase_document_id: string | null;
  step: Generated<string>;
  steps: Generated<Json>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Dies {
  code: string;
  compatible_press: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  last_run_at: Timestamp | null;
  location_id: string | null;
  maker_party_id: string | null;
  name: string | null;
  note: string | null;
  owner_party_id: string | null;
  product_id: string | null;
  run_count: Generated<number>;
  status: Generated<string>;
  total_produced_kg: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface DocumentLines {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string;
  document_id: string;
  id: Generated<string>;
  meta: Json | null;
  order_line_id: string | null;
  qty: Numeric | null;
  sort: Generated<number>;
  unit: string | null;
  unit_price: Numeric | null;
  vat_amount: Numeric | null;
  vat_rate: Numeric | null;
}

export interface Documents {
  account_id: string | null;
  agreed_kg: Numeric | null;
  amount: Numeric | null;
  barter_kg: Numeric | null;
  barter_sign: number | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: Generated<string>;
  date: Generated<Timestamp>;
  description: string | null;
  due_date: Timestamp | null;
  expense_category: string | null;
  expense_type: string | null;
  file_ids: Generated<string[]>;
  id: Generated<string>;
  kind: string;
  locked: Generated<boolean>;
  material_lot_id: string | null;
  method: string | null;
  note: string | null;
  number: string;
  order_id: string | null;
  party_id: string | null;
  posted_at: Timestamp | null;
  posted_by: string | null;
  print_count: Generated<number>;
  purchase_kind: string | null;
  received_kg: Generated<Numeric>;
  reported_by: string | null;
  reversed_by_document_id: string | null;
  reverses_document_id: string | null;
  settlement_basis_kg: Numeric | null;
  source_id: string | null;
  source_type: string | null;
  status: Generated<string>;
  tracking_no: string | null;
  transfer_id: string | null;
  unit_price: Numeric | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface ExpenseShares {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: string;
  document_id: string;
  id: Generated<string>;
  manual: Generated<boolean>;
  order_id: string;
  weight_kg: Numeric | null;
}

export interface FileLinks {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  entity: string;
  entity_id: string;
  file_id: string;
  id: Generated<string>;
}

export interface Files {
  caption: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  kind: string;
  mime: string;
  original_name: string;
  owner_entity: string | null;
  owner_id: string | null;
  sensitive: Generated<boolean>;
  sha256: string;
  size: Int8;
  sort_order: Generated<number>;
  storage_key: string;
  thumb_key: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface FreeNotes {
  amount: Numeric | null;
  conversion_request_id: string | null;
  converted_document_ids: Generated<string[]>;
  converted_transfer_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: string | null;
  id: Generated<string>;
  kg: Numeric | null;
  location_id: string | null;
  occurred_at: Timestamp | null;
  order_id: string | null;
  party_id: string | null;
  qty: Numeric | null;
  review_note: string | null;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  sensitive: Generated<boolean>;
  status: Generated<string>;
  telegram_message_id: string | null;
  text: string;
  topic: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface FxRates {
  at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  from_currency: string;
  id: Generated<string>;
  kind: string;
  rate: Numeric;
  source_text: string | null;
  to_currency: string;
}

export interface IdempotencyKeys {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  endpoint: string;
  id: Generated<string>;
  request_id: string;
  response: Json | null;
  user_id: string | null;
}

export interface ImportBatches {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  created_ids: Generated<Json>;
  errors: Generated<Json>;
  file_id: string | null;
  id: Generated<string>;
  kind: string;
  note: string | null;
  rows: Json;
  status: Generated<string>;
  trial: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Locations {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  kind: string;
  name: string;
  party_id: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface MaterialLots {
  alloy: string | null;
  batch_no: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  grade: string | null;
  id: Generated<string>;
  kg_per_unit: Numeric | null;
  kind: string;
  owner_party_id: string | null;
  responsible_user_id: string | null;
  tool_class: string | null;
  unit: Generated<string>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Notifications {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  entity: string | null;
  entity_id: string | null;
  group_key: string | null;
  id: Generated<string>;
  kind: string;
  read_at: Timestamp | null;
  telegram_sent_at: Timestamp | null;
  title: string;
  user_id: string;
}

export interface OpeningWeights {
  as_of: Timestamp;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: string | null;
  file_id: string | null;
  id: Generated<string>;
  item_id: string;
  item_type: string;
  kg: Numeric;
  location_id: string;
  locked: Generated<boolean>;
  reason: string | null;
  unit_cost: Numeric | null;
}

export interface OrderLines {
  calc_mode: Generated<string>;
  coating_gain_estimate_percent: Numeric | null;
  color: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: Generated<string>;
  description: string | null;
  die_id: string | null;
  discount_amount: Generated<Numeric>;
  discount_percent: Generated<Numeric>;
  file_id: string | null;
  filler_mm: Numeric | null;
  id: Generated<string>;
  kind: string;
  length_m: Numeric | null;
  load_type_label: string | null;
  material_kind: string | null;
  min_length_m: Numeric | null;
  name_ar: string | null;
  name_en: string | null;
  note: string | null;
  order_id: string;
  price_basis: Generated<string>;
  product_filler_id: string | null;
  product_id: string | null;
  qty_bars: Numeric | null;
  qty_is_estimate: Generated<boolean>;
  qty_kg: Numeric | null;
  qty_pieces: number | null;
  sort: Generated<number>;
  supply_method: string | null;
  unit_price: Numeric | null;
  updated_at: Generated<Timestamp>;
  vat_amount: Numeric | null;
  vat_rate: Numeric | null;
  version: Generated<number>;
  weight_g_per_m: Numeric | null;
  weight_unapproved: Generated<boolean>;
}

export interface OrderRevisions {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  order_id: string;
  reason: string | null;
  revision: number;
  snapshot: Json;
}

export interface Orders {
  approved_at: Timestamp | null;
  approved_by: string | null;
  archived: Generated<boolean>;
  cancel_reason: string | null;
  cost_confirmed_at: Timestamp | null;
  cost_confirmed_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: Generated<string>;
  delivery_days: number | null;
  destination_address: string | null;
  destination_city: string | null;
  destination_country: string | null;
  due_date: Timestamp | null;
  id: Generated<string>;
  internal_note: string | null;
  invoice_notes: string | null;
  number: string;
  order_date: Generated<Timestamp>;
  owner_user_id: string | null;
  party_id: string;
  payment_terms: Generated<string>;
  prepay_amount: Numeric | null;
  prepay_percent: Numeric | null;
  print_count: Generated<number>;
  revision: Generated<number>;
  settlement_basis: Generated<string>;
  status_sales: Generated<string>;
  title: string | null;
  updated_at: Generated<Timestamp>;
  valid_until: Timestamp | null;
  validity_text: string | null;
  version: Generated<number>;
}

export interface PackingLines {
  bars: number | null;
  bars_per_package: number | null;
  color: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  filler_mm: Numeric | null;
  gross_kg: Numeric | null;
  id: Generated<string>;
  is_partial: Generated<boolean>;
  length_m: Numeric | null;
  order_id: string | null;
  order_line_id: string | null;
  packages: Generated<number>;
  product_id: string | null;
  sort: Generated<number>;
  transfer_id: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  weight_kg: Numeric | null;
  weight_mode: Generated<string>;
}

export interface Parties {
  active: Generated<boolean>;
  address: string | null;
  city: string | null;
  country: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  default_currency: Generated<string>;
  id: Generated<string>;
  merged_into_id: string | null;
  name: string;
  name_ar: string | null;
  name_en: string | null;
  national_id: string | null;
  note: string | null;
  phones: Generated<string[]>;
  roles: Generated<string[]>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface ProductFillers {
  approved_at: Timestamp | null;
  approved_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  filler_mm: Numeric | null;
  id: Generated<string>;
  note: string | null;
  product_id: string;
  sample_length_m: Numeric | null;
  sample_weight_kg: Numeric | null;
  source: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  weight_g_per_m: Numeric;
}

export interface ProductionRunLines {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  die_id: string | null;
  filler_mm: Numeric | null;
  id: Generated<string>;
  length_m: Numeric | null;
  order_line_id: string | null;
  product_id: string;
  run_id: string;
  target_bars: number | null;
  target_kg: Numeric | null;
}

export interface ProductionRuns {
  close_reason: string | null;
  closed_at: Timestamp | null;
  closed_by: string | null;
  contract_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  due_at: Timestamp | null;
  factory_party_id: string;
  fee_document_id: string | null;
  fixed_fee: Numeric | null;
  good_kg: Generated<Numeric>;
  heat_treatment: string | null;
  id: Generated<string>;
  ingot_allocated_kg: Generated<Numeric>;
  ingot_consumed_kg: Numeric | null;
  location_id: string;
  note: string | null;
  number: string;
  press: string | null;
  rate_currency: Generated<string>;
  rate_per_kg: Numeric | null;
  rejected_kg: Generated<Numeric>;
  returned_material_kg: Generated<Numeric>;
  scrap_credit_rate: Numeric | null;
  scrap_kg: Generated<Numeric>;
  scrap_owner: string | null;
  service: Generated<string>;
  shift: string | null;
  shortage_document_id: string | null;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
  unexplained_kg: Numeric | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  weight_basis: string | null;
}

export interface Products {
  active: Generated<boolean>;
  alloy: string | null;
  category: string | null;
  code: string;
  colors: Generated<string[]>;
  common_lengths: Generated<ArrayType<Numeric>>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  drawing_version: string | null;
  id: Generated<string>;
  main_file_id: string | null;
  name_ar: string | null;
  name_en: string | null;
  name_fa: string;
  section_area_mm2: Numeric | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  weight_g_per_m_no_filler: Numeric | null;
}

export interface Reservations {
  bundle_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  kg: Numeric;
  material_lot_id: string | null;
  order_line_id: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface ScaleTickets {
  approved_at: Timestamp | null;
  approved_by: string | null;
  approved_for: Generated<string[]>;
  at: Timestamp | null;
  coating_run_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  file_id: string | null;
  gross_kg: Numeric | null;
  id: Generated<string>;
  net_direct_kg: Numeric | null;
  note: string | null;
  packaging_kg: Numeric | null;
  production_run_id: string | null;
  site: string | null;
  stage: string;
  status: Generated<string>;
  tare_kg: Numeric | null;
  ticket_no: string | null;
  transfer_id: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  expires_at: Timestamp;
  id: Generated<string>;
  last_seen_at: Generated<Timestamp>;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface Settings {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  key: string;
  updated_at: Generated<Timestamp>;
  value: Json | null;
  version: Generated<number>;
}

export interface ShareLinks {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  expires_at: Timestamp;
  id: Generated<string>;
  last_opened_at: Timestamp | null;
  open_count: Generated<number>;
  revoked: Generated<boolean>;
  scope_date: Timestamp | null;
  scope_id: string | null;
  scope_type: string;
  token_hash: string;
}

export interface StockMoves {
  at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: string | null;
  from_location_id: string | null;
  id: Generated<string>;
  item_id: string;
  item_type: string;
  kg: Numeric;
  note: string | null;
  owner_party_id: string | null;
  ref_id: string;
  ref_type: string;
  state_from: string | null;
  state_to: string | null;
  to_location_id: string | null;
  unit_cost: Numeric | null;
}

export interface TaskComments {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  file_id: string | null;
  id: Generated<string>;
  task_id: string;
  text: string | null;
  user_id: string;
}

export interface Tasks {
  assignee_user_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  done_at: Timestamp | null;
  done_file_id: string | null;
  done_note: string | null;
  due_at: Timestamp | null;
  id: Generated<string>;
  order_id: string | null;
  party_id: string | null;
  status: Generated<string>;
  title: string;
  transfer_id: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  voice_file_id: string | null;
}

export interface TelegramLinkCodes {
  code_hash: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  expires_at: Timestamp;
  id: Generated<string>;
  used_at: Timestamp | null;
  user_id: string;
}

export interface TransferLines {
  bars: number | null;
  bars_per_package: number | null;
  bundle_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  die_id: string | null;
  diff_note: string | null;
  diff_reason: string | null;
  id: Generated<string>;
  kg: Numeric | null;
  length_m: Numeric | null;
  material_lot_id: string | null;
  order_id: string | null;
  order_line_id: string | null;
  packages: number | null;
  received_at: Timestamp | null;
  received_kg: Numeric | null;
  transfer_id: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Transfers {
  bill_to_party_id: string | null;
  border: string | null;
  carrier_party_id: string | null;
  coating_run_id: string | null;
  consignee: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  delivery_term: string | null;
  departed_at: Timestamp | null;
  destination_address: string | null;
  destination_city: string | null;
  destination_country: string | null;
  dispatched_by: string | null;
  driver_name: string | null;
  driver_phone: string | null;
  eta: Timestamp | null;
  freight_cost: Numeric | null;
  freight_currency: Generated<string>;
  freight_document_id: string | null;
  freight_payer: string | null;
  from_location_id: string | null;
  id: Generated<string>;
  is_export: Generated<boolean>;
  kind: string;
  note: string | null;
  number: string;
  order_ids: Generated<string[]>;
  plate: string | null;
  print_count: Generated<number>;
  production_run_id: string | null;
  purchase_document_id: string | null;
  received_at: Timestamp | null;
  receiver_name: string | null;
  returns_transfer_id: string | null;
  status: Generated<string>;
  to_location_id: string | null;
  transport_mode: string | null;
  updated_at: Generated<Timestamp>;
  vehicle_type: string | null;
  version: Generated<number>;
  waybill_no: string | null;
}

export interface Users {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  failed_logins: Generated<number>;
  id: Generated<string>;
  locked_until: Timestamp | null;
  mobile: string;
  name: string;
  password_hash: string;
  permissions: Generated<string[]>;
  role: string;
  short_name: string | null;
  telegram_chat_id: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface DB {
  accounts: Accounts;
  allocations: Allocations;
  audit_log: AuditLog;
  bot_log: BotLog;
  bundle_lines: BundleLines;
  bundles: Bundles;
  coating_run_items: CoatingRunItems;
  coating_runs: CoatingRuns;
  contracts: Contracts;
  correction_requests: CorrectionRequests;
  counters: Counters;
  daily_reports: DailyReports;
  die_events: DieEvents;
  die_orders: DieOrders;
  dies: Dies;
  document_lines: DocumentLines;
  documents: Documents;
  expense_shares: ExpenseShares;
  file_links: FileLinks;
  files: Files;
  free_notes: FreeNotes;
  fx_rates: FxRates;
  idempotency_keys: IdempotencyKeys;
  import_batches: ImportBatches;
  locations: Locations;
  material_lots: MaterialLots;
  notifications: Notifications;
  opening_weights: OpeningWeights;
  order_lines: OrderLines;
  order_revisions: OrderRevisions;
  orders: Orders;
  packing_lines: PackingLines;
  parties: Parties;
  product_fillers: ProductFillers;
  production_run_lines: ProductionRunLines;
  production_runs: ProductionRuns;
  products: Products;
  reservations: Reservations;
  scale_tickets: ScaleTickets;
  sessions: Sessions;
  settings: Settings;
  share_links: ShareLinks;
  stock_moves: StockMoves;
  task_comments: TaskComments;
  tasks: Tasks;
  telegram_link_codes: TelegramLinkCodes;
  transfer_lines: TransferLines;
  transfers: Transfers;
  users: Users;
}
